#!/bin/bash

#pip install .
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode

apt-get update ##[edited]
apt-get install 'ffmpeg' 'libsm6' 'libxext6'  -y
#EOF
